### ISSUE TITLE
StackOverflowError with 1.3.4

### ISSUE THREAD

**Issue by kaciula** [yigit/android-priority-jobqueue#46] opened 2015-10-27 07:38 UTC
I am getting crash reports with StackOverflowError after updating the library to version 1.3.4. There is an endless number of this call:

....
com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:304) at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:304) at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:304) at 
.....

**Comment by yigit** [comment] 2015-11-03 07:20
Is this something you can reproduce?
Seems like that can happen after an update if you have a job X in the database way tooo many instances and they cannot be deserialized after the update. 

I may change that method not to be recursive but i'm not sure it will fix the issue or just avoid the crash. Are there any other logs? Or can you reproduce it somehow ?

**Comment by kaciula** [comment] 2015-11-03 08:37
Here is the full stacktrace. This is all I have and I cannot reproduce it. I only have one crash report so it might happen in very rare cases.

Fatal Exception: java.lang.StackOverflowError
       at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java)
       at java.lang.StringBuffer.append(StringBuffer.java)
       at java.io.StringWriter.write(StringWriter.java)
       at java.io.PrintWriter.doWrite(PrintWriter.java)
       at java.io.PrintWriter.write(PrintWriter.java)
       at java.io.PrintWriter.write(PrintWriter.java)
       at java.io.PrintWriter.write(PrintWriter.java)
       at java.io.PrintWriter.append(PrintWriter.java)
       at java.io.PrintWriter.append(PrintWriter.java)
       at java.io.PrintWriter.append(PrintWriter.java)
       at java.lang.Throwable.printStackTrace(Throwable.java)
       at java.lang.Throwable.printStackTrace(Throwable.java)
       at timber.log.Timber$Tree.getStackTraceString(Timber.java)
       at timber.log.Timber$Tree.prepareLog(Timber.java)
       at timber.log.Timber$Tree.w(Timber.java)
       at timber.log.Timber$1.w(Timber.java)
       at timber.log.Timber.w(Timber.java)
       at com.makanstudios.aurora.net.NetModule$3.e(NetModule.java)
       at com.path.android.jobqueue.log.JqLog.e(JqLog.java)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.safeDeserialize(SqliteJobQueue.java)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.createJobHolderFromCursor(SqliteJobQueue.java)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java)
.......................
com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:304) at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:304) at com.path.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:70) at com.path.android.jobqueue.JobManager.getNextJob(JobManager.java:515) at com.path.android.jobqueue.JobManager.access$800(JobManager.java:31) at com.path.android.jobqueue.JobManager$5.getNextJob(JobManager.java:683) at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:303) at java.lang.Thread.run(Thread.java:841)

**Comment by yigit** [comment] 2016-08-15 16:06
Closing this since I've just pushed v2 which hopefully should have this fixed.

**Closed by yigit** 2016-08-15 16:06 UTC
