### ISSUE TITLE
Database locking

### ISSUE THREAD

**Issue by eddnav** [yigit/android-priority-jobqueue#85] opened 2016-01-24 17:46 UTC
I'm getting the following crash for some time now in our bug tracker:

```Java
Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
       at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
       at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.onJobFetchedForRunning(SqliteJobQueue.java:287)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:205)
       at com.path.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:68)
       at com.path.android.jobqueue.JobManager.getNextJob(JobManager.java:273)
       at com.path.android.jobqueue.JobManager.access$400(JobManager.java:25)
       at com.path.android.jobqueue.JobManager$2.getNextJob(JobManager.java:423)
       at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:198)
       at java.lang.Thread.run(Thread.java:818)
```

I've been logging different scenarios to try and reproduce it, but I haven't been able to. In our bug tracker, It's always random, there's no pattern, except for the crash itself.

Any idea on what could be causing that exception? I've read on the actual SQLite issue: https://www.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked, everything seems to be in order in my code but that may not be the case.

**Comment by yigit** [comment] 2016-01-25 01:31
Thats weird, do you have full thread dump at the time this happens? Or create two job managers with the same ID by mistake?
I'm assuming you don't try to access JobManager's database directly and it never queries the database from multiple threads at the same time so this issue looks interesting.
Also, any patter about which devices this happen?

**Comment by eddnav** [comment] 2016-01-27 16:13
We use dependency injection to create the job manager, I'm pretty sure it's just created once and no we don't touch the JobManager's database directly.

Here's the dump:

```
Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
       at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
       at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.onJobFetchedForRunning(SqliteJobQueue.java:287)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:205)
       at com.path.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:68)
       at com.path.android.jobqueue.JobManager.getNextJob(JobManager.java:273)
       at com.path.android.jobqueue.JobManager.access$400(JobManager.java:25)
       at com.path.android.jobqueue.JobManager$2.getNextJob(JobManager.java:412)
       at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:198)
       at java.lang.Thread.run(Thread.java:865)
```
```
Compiler
       at dalvik.system.NativeStart.run(NativeStart.java)
```
```
Binder_1
dalvik.system.NativeStart.run (NativeStart.java)
```
```
Queue
java.lang.Object.wait (Object.java)
java.lang.Thread.parkFor (Thread.java:1229)
sun.misc.Unsafe.park (Unsafe.java:325)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2017)
java.util.concurrent.PriorityBlockingQueue.take (PriorityBlockingQueue.java:510)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation (DependencyPriorityBlockingQueue.java:180)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get (DependencyPriorityBlockingQueue.java:219)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:48)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:29)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:865)
```
```
java.lang.Object.wait (Object.java)
java.lang.Thread.parkFor (Thread.java:1229)
sun.misc.Unsafe.park (Unsafe.java:325)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2017)
java.util.concurrent.PriorityBlockingQueue.take (PriorityBlockingQueue.java:510)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation (DependencyPriorityBlockingQueue.java:180)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get (DependencyPriorityBlockingQueue.java:219)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:48)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:29)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:865)
```
```
Queue
java.lang.Object.wait (Object.java)
java.lang.Thread.parkFor (Thread.java:1229)
sun.misc.Unsafe.park (Unsafe.java:325)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2017)
java.util.concurrent.PriorityBlockingQueue.take (PriorityBlockingQueue.java:510)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation (DependencyPriorityBlockingQueue.java:180)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get (DependencyPriorityBlockingQueue.java:219)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:48)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:29)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:865)
```
```
ReferenceQueueDaemon
bject.wait (Object.java)
java.lang.Thread.run (Thread.java:865)
```
```
Queue
java.lang.Object.wait (Object.java)
java.lang.Thread.parkFor (Thread.java:1229)
sun.misc.Unsafe.park (Unsafe.java:325)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2017)
java.util.concurrent.PriorityBlockingQueue.take (PriorityBlockingQueue.java:510)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation (DependencyPriorityBlockingQueue.java:180)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get (DependencyPriorityBlockingQueue.java:219)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:48)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:29)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:865)
```
```
Binder_2
dalvik.system.NativeStart.run (NativeStart.java)
```
```
Signal Catcher
dalvik.system.NativeStart.run (NativeStart.java)
```
```
pool-5-thread-1
java.lang.Object.wait (Object.java)
java.lang.Thread.parkFor (Thread.java:1229)
sun.misc.Unsafe.park (Unsafe.java:325)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2017)
java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:865)
```
```
Crashlytics Exception Handler 1
dalvik.system.VMStack.getThreadStackTrace (VMStack.java)
java.lang.Thread.getAllStackTraces (Thread.java:545)
com.crashlytics.android.CrashlyticsUncaughtExceptionHandler.writeSessionEvent (CrashlyticsUncaughtExceptionHandler.java:929)
com.crashlytics.android.CrashlyticsUncaughtExceptionHandler.writeFatal (CrashlyticsUncaughtExceptionHandler.java:394)
com.crashlytics.android.CrashlyticsUncaughtExceptionHandler.handleUncaughtException (CrashlyticsUncaughtExceptionHandler.java:297)
com.crashlytics.android.CrashlyticsUncaughtExceptionHandler.access$200 (CrashlyticsUncaughtExceptionHandler.java:56)
com.crashlytics.android.CrashlyticsUncaughtExceptionHandler$7.call (CrashlyticsUncaughtExceptionHandler.java:277)
com.crashlytics.android.CrashlyticsUncaughtExceptionHandler$7.call (CrashlyticsUncaughtExceptionHandler.java:274)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun (ExecutorUtils.java:58)
io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run (BackgroundPriorityRunnable.java:13)
java.lang.Thread.run (Thread.java:865)
```
```
FInalizerWatchdogDaemon
.lang.Object.wait (Object.java)
java.lang.Object.wait (Object.java:364)
java.lang.Daemons$FinalizerWatchdogDaemon.run (Daemons.java:229)
java.lang.Thread.run (Thread.java:865)
```
```
Queue
bcore.io.Posix.poll (Posix.java)
libcore.io.BlockGuardOs.poll (BlockGuardOs.java:119)
libcore.io.IoBridge.isConnected (IoBridge.java:200)
libcore.io.IoBridge.connectErrno (IoBridge.java:161)
libcore.io.IoBridge.connect (IoBridge.java:112)
java.net.PlainSocketImpl.connect (PlainSocketImpl.java:192)
java.net.PlainSocketImpl.connect (PlainSocketImpl.java:459)
java.net.Socket.connect (Socket.java:864)
com.android.okhttp.internal.Platform.connectSocket (Platform.java:153)
com.android.okhttp.Connection.connect (Connection.java:101)
com.android.okhttp.internal.http.HttpEngine.connect (HttpEngine.java:294)
com.android.okhttp.internal.http.HttpEngine.sendSocketRequest (HttpEngine.java:255)
com.android.okhttp.internal.http.HttpEngine.sendRequest (HttpEngine.java:206)
com.android.okhttp.internal.http.HttpURLConnectionImpl.execute (HttpURLConnectionImpl.java:345)
com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse (HttpURLConnectionImpl.java:296)
com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode (HttpURLConnectionImpl.java:503)
com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode (HttpsURLConnectionImpl.java:136)
com.newrelic.agent.android.instrumentation.HttpsURLConnectionExtension.getResponseCode (HttpsURLConnectionExtension.java:236)
io.fabric.sdk.android.services.network.HttpRequest.code (HttpRequest.java:1390)
io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.handleResponse (DefaultSettingsSpiCall.java:79)
io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.invoke (DefaultSettingsSpiCall.java:66)
io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData (DefaultSettingsController.java:63)
io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData (DefaultSettingsController.java:47)
io.fabric.sdk.android.services.settings.Settings.loadSettingsData (Settings.java:139)
io.fabric.sdk.android.Onboarding.doInBackground (Onboarding.java:80)
io.fabric.sdk.android.Onboarding.doInBackground (Onboarding.java:26)
io.fabric.sdk.android.InitializationTask.doInBackground (InitializationTask.java:46)
io.fabric.sdk.android.InitializationTask.doInBackground (InitializationTask.java:11)
io.fabric.sdk.android.services.concurrency.AsyncTask$2.call (AsyncTask.java:294)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.lang.Thread.run (Thread.java:865)
```
```
Thread-759
java.lang.Object.wait (Object.java)
java.util.concurrent.FutureTask.get (FutureTask.java:162)
com.crashlytics.android.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException (CrashlyticsExecutorServiceWrapper.java:47)
com.crashlytics.android.CrashlyticsUncaughtExceptionHandler.uncaughtException (CrashlyticsUncaughtExceptionHandler.java:274)
java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:693)
java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:690)
```
```
GC
dalvik.system.NativeStart.run (NativeStart.java)
```
```
FinalizerDaemon
java.lang.Object.wait (Object.java)
java.lang.Object.wait (Object.java:401)
java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:102)
java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:73)
java.lang.Daemons$FinalizerDaemon.run (Daemons.java:172)
java.lang.Thread.run (Thread.java:865)
```
```
main
android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow (SQLiteConnection.java)
android.database.sqlite.SQLiteConnection.executeForCursorWindow (SQLiteConnection.java:845)
android.database.sqlite.SQLiteSession.executeForCursorWindow (SQLiteSession.java:836)
android.database.sqlite.SQLiteQuery.fillWindow (SQLiteQuery.java:62)
android.database.sqlite.SQLiteCursor.fillWindow (SQLiteCursor.java:144)
android.database.sqlite.SQLiteCursor.getCount (SQLiteCursor.java:133)
android.database.AbstractCursor.moveToPosition (AbstractCursor.java:197)
android.database.AbstractCursor.moveToNext (AbstractCursor.java:245)
com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.countReadyJobs (SqliteJobQueue.java:153)
com.path.android.jobqueue.cachedQueue.CachedJobQueue.countReadyJobs (CachedJobQueue.java:55)
com.path.android.jobqueue.JobManager.countReadyJobs (JobManager.java:135)
com.path.android.jobqueue.JobManager.access$900 (JobManager.java:25)
com.path.android.jobqueue.JobManager$2.countRemainingReadyJobs (JobManager.java:467)
com.path.android.jobqueue.executor.JobConsumerExecutor.isAboveLoadFactor (JobConsumerExecutor.java:100)
com.path.android.jobqueue.executor.JobConsumerExecutor.doINeedANewThread (JobConsumerExecutor.java:63)
com.path.android.jobqueue.executor.JobConsumerExecutor.considerAddingConsumer (JobConsumerExecutor.java:43)
com.path.android.jobqueue.JobManager.notifyJobConsumer (JobManager.java:243)
com.path.android.jobqueue.JobManager.ensureConsumerWhenNeeded (JobManager.java:229)
com.path.android.jobqueue.JobManager.onNetworkChange (JobManager.java:389)
com.path.android.jobqueue.network.NetworkUtilImpl$1.onReceive (NetworkUtilImpl.java:25)
android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:776)
android.os.Handler.handleCallback (Handler.java:733)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5372)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:970)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:786)
dalvik.system.NativeStart.main (NativeStart.java)
```
```
Binder_3
dalvik.system.NativeStart.run (NativeStart.java)
```
```
OkHttp ConnectionPool
java.lang.Object.wait (Object.java)
java.lang.Thread.parkFor (Thread.java:1229)
sun.misc.Unsafe.park (Unsafe.java:325)
java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:197)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2056)
java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:435)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:865)
```

Regarding device patterns, there is none sadly. The most affected are Samsung devices but not in an unexpected way (49%), same story with Android versions, with Android 4 leading (46%).

Let me know if you find anything that seems off, thanks

**Comment by yigit** [comment] 2016-01-27 16:34
interesting, seems like it happens when network change happens at the same time job is scheduled.
I actually noticed something even worse, the network change arrives on the main thread:/. That issue is already fixed in the new JobManager2's thread model. (I don't have a snapshot yet but I can publish if you like adventure :) )
On the other hand, this exception should not be happening because access to the queue is guaranteed to be thread safe :/. So seems like some method is missing sync. I'll check, thanks a lot!

**Comment by yigit** [comment] 2016-01-28 02:45
I don't think you have the latest version because lines do not match.
Also, both of these methods access the sqlite database using the `persistentJobQueue` itself as a lock so I'm now sure how they both enter to it :/.

https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/path/android/jobqueue/JobManager.java#L151

https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/path/android/jobqueue/JobManager.java#L537

Do you mind updating to the latest version?

**Comment by eddnav** [comment] 2016-01-28 14:38
Sure thing, I'll make sure it's updated. Thanks.

**Comment by yigit** [comment] 2016-02-15 22:45
Hi, I've published SNAPSHOT version of v2 on maven central. All test are passing so should be fairly stable. It is still a snapshot not because it is unstable but because I'm planning more api deprecations and new features before v2.0. 
I would be happy if you can give it a try and lmk if it fixes your issue (it should because this version does not have any multi-threading internally).

**Comment by Faltenreich** [comment] 2016-03-30 07:37
Hello,
I'm getting the same exception from time to time for following versions:

- com.path:android-priority-jobqueue:1.1.2
- com.github.yigit:android-priority-jobqueue:v2-SNAPSHOT

I did not try the current alpha yet but if there have been no changes in this direction / to the internal database handling, I'm afraid this behavior is still in this otherwise awesome library.

See a crashreport from the v2-SNAPSHOT:
```
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:559)
	at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
	at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.delete(SqliteJobQueue.java:172)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.remove(SqliteJobQueue.java:164)
	at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.remove(CachedJobQueue.java:48)
	at com.birbit.android.jobqueue.JobManagerThread.removeJob(JobManagerThread.java:540)
	at com.birbit.android.jobqueue.JobManagerThread.handleRunJobResult(JobManagerThread.java:455)
	at com.birbit.android.jobqueue.JobManagerThread.access$200(JobManagerThread.java:37)
	at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:226)
	at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
	at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:212)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by yigit** [comment] 2016-03-30 08:34
by any chance are you creating multiple job managers with the same id (or by mistake)? There is no reason for this to happen and V2 accesses database only from 1 thread so it cannot be a multi-threading issue.

**Comment by yigit** [comment] 2016-03-30 08:36
also is this something that you can reproduce? if so, can you create a sample app that I can debug? Also, what happens when app is in this state? Does it recover after a restart?

**Comment by Faltenreich** [comment] 2016-03-30 08:46
I handle the JobManager as a singleton in a proxy class, so it should only be instantiated once.

Unfortunately I am not able to reproduce this error since it appears unexpected at different circumstances - at least from my point of view. After the SQLiteDatabaseLockedException occurs, the app crashes with the typical "app has stopped"-dialog and recovers itself after a restart. Then it seems to be working as expected.

**Comment by yigit** [comment] 2016-03-30 09:04
Idk how to solve this but I have an idea:

If you have stack trace of all threads in your app at the time of crash, it might be helpful. 
In V2, threads are named so it can have valuable information about what is going on. 

Also, by any chance, do you have multiple processes? Maybe JobManagers in different processes are clashing?

**Comment by Faltenreich** [comment] 2016-03-30 11:28
The thread in which the SQLiteDatabaseLockedException is occurring is named "Thread: job-manager-7324". Sadly this is everything the HockeyApp CrashManager is providing me.

I do not have multiple processes, only an application that starts a service in a different thread. Both are using your JobQueue in the same process.

I will try to track the problem down by filing the logcat by myself but due to the late and seemingly random appearances of the bug it could take some time.

**Comment by yigit** [comment] 2016-06-22 06:22
Hey, can you try 2.0-alpha5 if possible. It has a new model which should avoid all locking issues.

**Closed by yigit** 2016-06-22 06:22 UTC

**Comment by TasneemBohra** [comment] 2017-08-08 07:13
@yigit  I am using `com.birbit:android-priority-jobqueue:2.0.1` and still getting this exception. And I am using single Job Queue.

**Comment by dimmduh** [comment] 2017-11-29 07:18
The problem still exists
`android.database.sqlite.SQLiteConnection.nativeExecute (SQLiteConnection.java)
android.database.sqlite.SQLiteConnection.execute (SQLiteConnection.java:699)
android.database.sqlite.SQLiteSession.beginTransactionUnchecked (SQLiteSession.java:323)
android.database.sqlite.SQLiteSession.beginTransaction (SQLiteSession.java:298)
android.database.sqlite.SQLiteDatabase.beginTransaction (SQLiteDatabase.java:510)
android.database.sqlite.SQLiteDatabase.beginTransaction (SQLiteDatabase.java:421)
com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.delete (SqliteJobQueue.java:205)
com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.remove (SqliteJobQueue.java:201)
com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.remove (CachedJobQueue.java:51)
com.birbit.android.jobqueue.JobManagerThread.removeJob (JobManagerThread.java:561)
com.birbit.android.jobqueue.JobManagerThread.handleRunJobResult (JobManagerThread.java:472)
com.birbit.android.jobqueue.JobManagerThread.access$300 (JobManagerThread.java:35)
com.birbit.android.jobqueue.JobManagerThread$1.handleMessage (JobManagerThread.java:237)
com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume (PriorityMessageQueue.java:39)
com.birbit.android.jobqueue.JobManagerThread.run (JobManagerThread.java:222)
java.lang.Thread.run (Thread.java:818)`

**Comment by biliboss** [comment] 2017-11-29 12:51
Hi @yigit i have this issue too http://crashes.to/s/e4880d73033

**Comment by chainsingh** [comment] 2018-02-07 11:33
i am also facing the same issue.. but there are many processes in which job manager is running.. Is that not supported?

FATAL EXCEPTION: job-manager
                                                   Process: com.yawasa.avanti.prod, PID: 10175
                                                   android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
                                                       at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
                                                       at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
                                                       at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
                                                       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:507)
                                                       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:418)
                                                       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.delete(SqliteJobQueue.java:205)
                                                       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.remove(SqliteJobQueue.java:201)
                                                       at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.remove(CachedJobQueue.java:51)
                                                       at com.birbit.android.jobqueue.JobManagerThread.removeJob(JobManagerThread.java:561)
                                                       at com.birbit.android.jobqueue.JobManagerThread.handleRunJobResult(JobManagerThread.java:472)
                                                       at com.birbit.android.jobqueue.JobManagerThread.access$300(JobManagerThread.java:35)
                                                       at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:237)
                                                       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
                                                       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
                                                       at java.lang.Thread.run(Thread.java:761)


02-06 21:35:49.483 11969-12020/? E/AndroidRuntime: FATAL EXCEPTION: job-manager
                                                   Process: com.yawasa.avanti.prod:acra, PID: 11969
                                                   android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
                                                       at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
                                                       at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
                                                       at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
                                                       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:507)
                                                       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:418)
                                                       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.delete(SqliteJobQueue.java:205)
                                                       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.remove(SqliteJobQueue.java:201)
                                                       at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.remove(CachedJobQueue.java:51)
                                                       at com.birbit.android.jobqueue.JobManagerThread.removeJob(JobManagerThread.java:561)
                                                       at com.birbit.android.jobqueue.JobManagerThread.handleRunJobResult(JobManagerThread.java:472)
                                                       at com.birbit.android.jobqueue.JobManagerThread.access$300(JobManagerThread.java:35)
                                                       at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:237)
                                                       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
                                                       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
                                                       at java.lang.Thread.run(Thread.java:761)

**Comment by jandoblelim** [comment] 2018-08-07 04:04
Still occurring too.
