### ISSUE TITLE
JobsQueue doesn't work after calling 'cancelJobsInBackground' method (CRITICAL)

### ISSUE THREAD

**Issue by fraggjkee** [yigit/android-priority-jobqueue#19] opened 2015-04-10 21:36 UTC
Hello @yigit. First of all, thank you for your great work :) 

I faced with one quite serious problem after attempts to use the newly added jobs cancelation mechanism (added in v1.3).

Seems that after calling `jobManager.cancelJobsInBackground` JobsQueue brakes itself and doesn't execute new jobs anymore.

```java
public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final JobManager jobManager = MyApplication.getInstance().getJobManager();

        Button doJobButton = (Button) findViewById(R.id.button1);
        doJobButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                jobManager.addJobInBackground(new SimpleJob());
            }
        });

        Button cancelJobsButton = (Button) findViewById(R.id.button2);
        cancelJobsButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                jobManager.cancelJobsInBackground(new CancelResult.AsyncCancelCallback() {
                    @Override
                    public void onCancelled(CancelResult cancelResult) {
                        Collection<Job> cancelledJobs = cancelResult.getCancelledJobs();
                        Collection<Job> failedToCancelJobs = cancelResult.getFailedToCancel();
                        jobManager.clear();
                        jobManager.stop();
                        Log.d(MainActivity.class.getSimpleName(), "JobsQueue: cancelled jobs - " + cancelledJobs.size()
                                + ", failed to cancel jobs - " + failedToCancelJobs.size());
                    }
                }, TagConstraint.ALL, SimpleJob.TAG);
            }
        });
    }

    @Override
    protected void onStart() {
        super.onStart();
        EventBus.getDefault().register(this);
    }

    @Override
    protected void onPause() {
        super.onPause();
        EventBus.getDefault().unregister(this);
    }

    public void onEventMainThread(JobDoneEvent event) {
        Toast.makeText(this, "Job done", Toast.LENGTH_SHORT).show();
    }

    private static class SimpleJob extends Job {

        public static String TAG = SimpleJob.class.getSimpleName();

        protected SimpleJob() {
            super(new Params(1).addTags(TAG));
        }

        @Override
        public void onAdded() {
            Log.d(TAG, "onAdded");
        }

        @Override
        public void onRun() throws Throwable {
            Log.d(TAG, "onRun");
            Thread.sleep(TimeUnit.SECONDS.toMillis(3));
            EventBus.getDefault().post(new JobDoneEvent());
        }

        @Override
        protected void onCancel() {
            Log.d(TAG, "onCancel");
        }

        @Override
        protected int getRetryLimit() {
            return 5;
        }

        @Override
        protected boolean shouldReRunOnThrowable(Throwable throwable) {
            return true;
        }
    }

    private static class JobDoneEvent {

    }
}
```

A super-easy way to reproduce the problem using the code from above:
1. Add several jobs the the queue, just click 3-4 times on `addJobButton`
2. When there are some active/waiting jobs in the queue still, click `cancelJobsButton`.
3. Try to add a new job (again, by clicking the Add Job button)... Nothing happens. There will be a call to `onAdded` method of our `SimpleJob`, but `onRun` won't be ever called.
4. What's even *more important*, JobsQueue will be in this "broken" state even after application restart  (close the app by pressing system Back button and launch the app again). The only way to fix this is to kill the whole process completely. So this is an indication of another problem which probably isn't connected to cancelation itself: JobsQueue keeps itself alive even if application was closed. I assume if we set `minConsumerCount` to something greater than 0 then JobsQueue will do attempts to keep at least one consumer thread alive draining battery life even if your application was closed.

I'm using Android 5.0 on my test device. By the way, here is my config if it helps:
```java
 Configuration configuration = new Configuration.Builder(this)
                .minConsumerCount(0)
                .maxConsumerCount(3)
                .loadFactor(3)
                .consumerKeepAlive(60)
                .customLogger(new JobQueueLogger())
                .build();
```

**Comment by yigit** [comment] 2015-04-11 02:15
in your cancelation result, you are calling `jobmanager.stop()`. I think that is the problem ?

**Comment by fraggjkee** [comment] 2015-04-11 06:38
@yigit thank you for your response. you're right, that's the reason of the problem in this particular example. I just was trying to find a way to 'reset' JobsQueue's state to make it alive (i.e. call `onRun` of newly added jobs) and forgot to comment these two lines. so the code from above should work if we get rid of unnecessary calls to `cancel` and `stop` methods. Sorry for confusing. But in my project the problem still exists unfortunately (I don't use `clear` and `stop` there) and so far I cannot understand what is the difference and what goes wrong there in comparing with the sample code I've posted here.

I just realized that the problem is connected with jobs grouping by somehow (`groupBy()` method). Everything works well if I don't group requests, JobsQueue executes requests after cancellation. But if jobs belong to the same group then I see only this in my logs (after cancellation of several past jobs from the same group):

> D/ConversationFragment﹕ Messages queue: cancelled jobs - 3, failed to cancel jobs - 0
> D/JobsQueue﹕ added job id: -2147483644 class: SendMessageJob priority: 1 delay: 0 group : group persistent: false requires network: false
D/JobsQueue﹕ pool-2-thread-1: load factor check. false = (1 < 0)|| (1 * 3 < 0 + 0). consumer thread: false
D/JobsQueue﹕ main: load factor check. false = (1 < 0)|| (1 * 3 < 0 + 0). consumer thread: false

...and nothing else, there is a call to `onAdded` method of new jobs but `onRun` never gets called for some reason. so it looks like JobsQueue is waiting for some job to complete but there are no jobs in the queue and all previously existing jobs were successfully cancelled as cancellation callback says. @yigit may be do you have any ideas?

**Comment by yigit** [comment] 2015-04-11 09:43
hmm, maybe cancelation does not clear group flags properly. Can you check if it works when you add a job from a new group? If so, I can probably reproduce this in a test case and fix it.

Thanks for the detailed report, lmk if a job from a new group works fine and I'll work on the fix.

**Comment by fraggjkee** [comment] 2015-04-12 12:02
> Can you check if it works when you add a job from a new group?

@yigit yes it works correctly in this case

**Comment by yigit** [comment] 2015-04-12 20:03
Great, looks like a problem when cleaning running job groups list.
I should be able to reproduce, will work on it, thanks!

**Comment by yigit** [comment] 2015-04-12 23:50
Hi, unfortunately, I'm unable to reproduce this.

I created test cases for canceling jobs while running / before running for both persistent and non-persistent jobs (with groups) and all tests pass.

Then I created a test app from the code you've provided, removing jobManager.stop() / jobManager.clear() calls, it worked again.

Here are the logs from the sample app I created:
https://gist.github.com/yigit/5379502d368d0a02327a

And here is my sample activity:
https://gist.github.com/yigit/f9a5efa4967300e6b935

Can you provide a test app w/ source that reproduces the issue?

**Comment by fraggjkee** [comment] 2015-04-13 11:34
Hi @yigit. Seems that we need a little bit more complex test project to reproduce the problem. I prepared it for you - https://gist.github.com/fraggjkee/04fcf2a3b47e36d723eb

run the app -> disable network -> post 2-3 jobs -> cancel them -> enable network -> try to post a new job

I understand that this particular use-case is quite uncommon but I cannot get an idea how I break JobsQueue's normal flow anyway... Thank you for your help.

**Comment by yigit** [comment] 2015-04-14 08:07
Thanks a lot, i can reproduce the error in the test app. From the logs, it seems like JobManager#countReadyJobs is failing (returns 0) so JobManager thinks it does not need to create any consumer.

This is very helpful, i'll try to move it to a test case an work on the fix.

**Comment by yigit** [comment] 2015-04-20 02:48
Ok, finally good news. I was able to write a test that reproduces it and fixed it. Apparently, this was related to canceling a job while it is running and job fails. JobManager was not removing it from running jobs group because it does not go through remove path (by job executor).

It was tricky to fix but i think it is good now, thanks for the report!
I'll soon create a CL and after approval, will push a new version.

**Comment by Yazazzello** [comment] 2015-04-20 06:30
Thank you very much!

**Comment by yigit** [comment] 2015-04-20 06:40
I just pushed 1.3.1. Please lmk if it fixes your app so I can close the issue or further debug it.

**Comment by fraggjkee** [comment] 2015-04-20 15:59
Thank you @yigit, version 1.3.1 works great :)

**Comment by yigit** [comment] 2015-04-20 20:05
yay!

**Closed by yigit** 2015-04-20 20:05 UTC
