### ISSUE TITLE
Persist job will execute immediately

### ISSUE THREAD

**Issue by mahuafactory** [yigit/android-priority-jobqueue#68] opened 2015-12-25 09:29 UTC
I found that,if I add a persist job that with delay time like 10s,then I kill the app and restart the app .

sqlHelper.resetDelayTimesTo(JobManager.NOT_DELAYED_JOB_DELAY);

According the code above,the job will be reset,and then will be execute immediately.Does it normal?

**Comment by mahuafactory** [comment] 2015-12-25 09:31
By the way,I love this lib.Our app has 50 million users in China.And we want to use this.So we are research the code.THX for your work

**Comment by yigit** [comment] 2015-12-25 20:24
Yes, this is the intended behavior, see the delay section here:
https://github.com/yigit/android-priority-jobqueue/wiki/Job-Configuration

The problem is that, after a restart, we have no way of knowing whether the device restarted or not. When device is restarted, the CPU time may be reset so the job may never restart.
We could rely on wall clock but thats also not reliable since it might be changed manually.

We may introduce an API that relies on wall clock (maybe something like `setRunAfter(epocTime)`). 
Right now, JobManager does not wake up your app for delayed jobs. Maybe after GMS integration, this might be a feasible option.

**Comment by yigit** [comment] 2016-01-22 05:21
For 2.0, I'm considering moving JobQueue to wall clock. It will make integrating with GCM network manager.

**Comment by yigit** [comment] 2016-02-15 18:35
fixed in v2.

**Closed by yigit** 2016-02-15 18:35 UTC
