### ISSUE TITLE
Crash on app start after throwing exceptions on onRun(). Improper usage or bug?

### ISSUE THREAD

**Issue by juliomarcos** [yigit/android-priority-jobqueue#157] opened 2016-05-18 15:36 UTC
After throwing exceptions on onRun() the app crashes when it starts again. And it only stops crashing if the app data is cleared.

Is this improper usage or a bug?

Using **compile 'com.birbit:android-priority-jobqueue:2.0.0-alpha2'**

```
    Process: , PID: 23806
    java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.birbit.android.jobqueue.scheduling.FrameworkScheduler.onStartJob(android.app.job.JobParameters)' on a null object reference
        at android.app.job.JobService$JobHandler.handleMessage(JobService.java:130)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.birbit.android.jobqueue.scheduling.FrameworkScheduler.onStartJob(android.app.job.JobParameters)' on a null object reference
        at com.birbit.android.jobqueue.scheduling.FrameworkJobSchedulerService.onStartJob(FrameworkJobSchedulerService.java:76)
        at android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5443) 
        at java.lang.reflect.Method.invoke(Native Method)
```

That's how I'm configuring the job
```
        super(
                new Params(1).
                    requireNetwork().
                    persist()
        );
```

**Comment by yigit** [comment] 2016-05-19 05:08
Can you share how you are creating the job manager and binding it to the job scheduler? 
Did you go through this?
https://github.com/yigit/android-priority-jobqueue/wiki/Integration-with-JobScheduler-and-GcmNetworkManager

**Comment by juliomarcos** [comment] 2016-05-20 18:22
Sure, here it is.

```
Configuration.Builder builder = new Configuration.Builder(context)
                .customLogger(new CustomLogger() {
                    private static final String TAG = "JOBS";
                    @Override
                    public boolean isDebugEnabled() {
                        return true;
                    }

                    @Override
                    public void d(String text, Object... args) {
                        Log.d(TAG, String.format(text, args));
                    }

                    @Override
                    public void e(Throwable t, String text, Object... args) {
                        Log.e(TAG, String.format(text, args), t);
                    }

                    @Override
                    public void e(String text, Object... args) {
                        Log.e(TAG, String.format(text, args));
                    }
                })
                .minConsumerCount(1) //always keep at least one consumer alive
                .maxConsumerCount(1) //up to 1 consumers at a time
                .loadFactor(1) //1 job per consumer
                .consumerKeepAlive(120); //wait 2 minutes
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            builder.scheduler(
                    FrameworkJobSchedulerService.createSchedulerFor(context,
                    MyJobService.class), false);
        } else {
            int enableGcm = GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(context);
            if (enableGcm == ConnectionResult.SUCCESS) {
                builder.scheduler(
                        GcmJobSchedulerService.createSchedulerFor(context,
                        MyGcmJobService.class), false);
            }
        }
        return new JobManager(builder.build());
```

And yes, I went through that tutorial.

**Comment by sideprojecteu** [comment] 2016-05-21 08:27
+1

**Comment by yigit** [comment] 2016-05-28 17:44
sorry for the delay.
Seems like the problem is that, by the time framework scheduler service is created, your JobManager is not yet configured. I should change API to ensure that it requires a job manager before trying to get it.

I'll modify the API to avoid such mistakes, meanwhile, you can work around the issue by making sure that JobManager is created when service is created.

**Comment by yigit** [comment] 2016-05-28 19:02
hi, 
I've just shipped alpha3 and updated the WIKI.
Now you have to provide `getJobManager` method. This will allow the scheduler to avoid NPE.
I've also fixed internals not to receive a NPE.

https://github.com/yigit/android-priority-jobqueue/wiki/Integration-with-JobScheduler-and-GcmNetworkManager

**Closed by yigit** 2016-05-28 19:02 UTC
